### ISSUE TITLE
Error with Replay Buffer

### ISSUE THREAD

**Issue by JanoschMenke** [GuoJeff/saturn#1]
Hi Jeff,

When trying to run Saturn I get the following error message for the replay buffer.

```
Traceback (most recent call last):
  File "/app/saturn/saturn.py", line 76, in <module>
    reinforcement_learning_agent = ReinforcementLearningAgent(
  File "/app/saturn/goal_directed_generation/reinforcement_learning.py", line 66, in __init__
    self.oracle = self.replay_buffer.prepopulate_buffer(self.oracle)
  File "/app/saturn/experience_replay/replay_buffer.py", line 138, in prepopulate_buffer
    rewards = np.empty((len(oracle), len(mols)))
TypeError: object of type 'Oracle' has no len()
```

This is the part of the config
```
    "experience_replay": {
      "memory_size": 100,  
      "sample_size": 10, 
      "smiles": []  
   ```
   
   Do you know what could cause this?

**Comment by JanoschMenke** [comment]
Sorry realized I am in the wrong version of saturn

**Comment by GuoJeff** [comment]
Hi Janosch,

Yes, sorry for this, in the version here (old) and also in the public version here: https://github.com/schwallergroup/saturn, there is a typo in the function that I missed pushing. I will make the fix now in the other repo.
